name: Run tests MacOs
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - dotty-experimental
concurrency:
  group: macOS-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Test runtime
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        scala: [3, "3-next"]
        gc: [immix]
        include:
          - scala: 3.1.3
            gc: immix

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/macos-setup-env
        id: setup
        with:
          scala-version: ${{matrix.scala}}

      - name: Test runtime
        run: >
          export SCALANATIVE_GC=${{matrix.gc}} &&
          sbt "test-runtime ${{matrix.scala}}"

  run-scripted-tests:
    name: Scripted tests
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        scala: [3, "3-next"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/macos-setup-env
        with:
          scala-version: ${{matrix.scala}}

      - name: Test scripted
        run: |
          export LLVM_BIN=$(brew --prefix llvm@15)/bin
          sbt "test-scripted ${{matrix.scala}}"
